export const storeNames = [
    "Gurudattha Supermarket Kowthalam",
    "Shiva Lila Supermarket Holagunda",
    "RRR Supermarket",
    "Sree Bhavani Supermarket Kosigi",
    "SLV Supermarket Dhone Kurnool",
    "Sana Supermarket",
    "Tanvika Supermarket Velgodu",
    "Deepthi Supermarket Koilakuntla",
    "Adil Supermarket Porumamilla",
    "B Mart Gadivemula",
    "Bharath Supermarket Komarolu",
    "Sri Gowri Shankar Supermarket Atmakur",
    "The Big Supermarket Kunta",
    "MV Supermarket Sundipenta",
    "SS Supermarket Gajulapalle",
    "Manoj Supermarket Mydukur",
    "Vinutana Supermarket Bestawaripeta",
    "Gold Supermarket ITI Circle Kadapa",
    "Gold Supermarket Navodaya Colony ATP",
    "ATP Store",
    "Gold Supermarket Saipeta Kadapa",
    "Gold Supermarket Venugopal Nagar ATP",
    "Gold Supermarket NGO Colony Kadapa",
    "Gold Supermarket CK Dinne Kadapa",
    "Gold Supermarket Ganesha Nagar ATP",
    "Gold Supermarket Angadi Veedhi Kadapa",
    "Gold Supermarket Padarupalli Nellore",
    "A1 Supermarket",
    "Shobha Enterprises Nellore",
    "Ganesh Super Market Kavali",
    "Naveena Supermarket Udayagiri",
    "Pushpa Supermarket Manubolu",
    "Sri Lakshmi Supermarket Nellore",
    "CNR Supermarket Nellore",
    "Sri Kamakshi Supermarket Nellore",
    "Sai Sreenivasa Supermarket Nellore",
    "Sri Venkataramana Supermarket Ulavapadu",
    "Rihan Supermarket Indukurpet",
    "KNR Super Mart Atmakur Nellore",
    "Sri Hari",
    "Ashta Lakshmi",
    "Venkata Padmaja",
    "V Mart",
    "Sri Padmavathi Supermarket",
    "Sri Shiridi Sai",
    "AA Supermarket Rayachoty"
  ];