export const storeNames = [
  "Gurudattha Supermarket Kowthalam",
  "Shiva Lila Supermarket Holagunda",
  "RRR Supermarket",
  "Sree Bhavani Supermarket Kosigi",
  "SLV Supermarket Dhone Kurnool",
  "Sana Supermarket",
  "Tanvika Supermarket Velgodu",
  "Deepthi Supermarket Koilakuntla",
  "Adil Supermarket Porumamilla",
  "B Mart Gadivemula",
  "Bharath Supermarket Komarolu",
  "Sri Gowri Shankar Supermarket Atmakur",
  "The Big Supermarket Kunta",
  "MV Supermarket Sundipenta",
  "SS Supermarket Gajulapalle",
  "Manoj Supermarket Mydukur",
  "Vinutana Supermarket Bestawaripeta",
  "Gold Supermarket ITI Circle Kadapa",
  "Gold Supermarket Navodaya Colony ATP",
  "ATP Store",
  "Gold Supermarket Saipeta Kadapa",
  "Gold Supermarket Venugopal Nagar ATP",
  "Gold Supermarket NGO Colony Kadapa",
  "Gold Supermarket CK Dinne Kadapa",
  "Gold Supermarket Ganesha Nagar ATP",
  "Gold Supermarket Angadi Veedhi Kadapa",
  "Gold Supermarket Padarupalli Nellore",
  "A1 Supermarket",
  "Shobha Enterprises Nellore",
  "Ganesh Super Market Kavali",
  "Naveena Supermarket Udayagiri",
  "Pushpa Supermarket Manubolu",
  "Sri Lakshmi Supermarket Nellore",
  "CNR Supermarket Nellore",
  "Sri Kamakshi Supermarket Nellore",
  "Sai Sreenivasa Supermarket Nellore",
  "Sri Venkataramana Supermarket Ulavapadu",
  "Rihan Supermarket Indukurpet",
  "KNR Super Mart Atmakur Nellore",
  "Sri Hari",
  "Ashta Lakshmi",
  "Venkata Padmaja",
  "V Mart",
  "Sri Padmavathi Supermarket",
  "Sri Shiridi Sai",
  "Veerabhadra Supermarket Kadapa",
  "Sai Krupa Supermarket Kadapa",
  "Sree Lakshmi Narasimha Agencies Kadapa",
  "J S Mart Kamalapuram",
  "KKR Supermarket Buggaletipalle",
  "Satesh Enterprises Madhavaram",
  "Ahobila Narasimha Swami Agency Kadapa",
  "Sidhout Onestop Supermarket Siddhavatam",
  "PVS Shopping Mall Akkayapalli",
  "Lakshmi balaji Supermarket B Matam",
  "KR Mart Tirupati",
  "VSR Mart Rompicherla",
  "Vijay Krishna V Mart Tirupati",
  "Grand Mart Palamaner",
  "Vijetha Supermarket Varadaiahpalem",
  "Nandhini Supermarket West Gudur",
  "S Mart Tirupati",
  "SLV Supermarket Chinnagottigallu",
  "Sri Kamakshi Supermarket Marrikuntapalle",
  "Sri Laxmi Ganapathi Supermarket Kandhur",
  "SSPS Supermarket Pileru",
  "ANR Maart V Kota",
  "Nirmala E Supermarket Gudur",
  "Sri Padmavathi Venkateshwara Supermarket",
  "JK Supermarket Tirupati",
  "Veerabhadra Supermarket Galiveedu",
  "MG Star Mart Veeraballi",
  "Sri Venkateswara Supermarket Rayachoty",
  "Sree Vari Supermarket Madanapalle",
  "Ravi and Sons Supermarket Chowdepalli",
  "Sai Supermarket T Sundupalli",
  "Babu Supermarket B Kothakota",
  "A1 Alfaz Supermarket Gurramkonda",
  "Guru Supermarket T Sundupalli",
  "Goddemma Thalli Supermarket Tanakal",
  "Shiva Shakthi Supermarket Rayachoty",
  "AA Supermarket Rayachoty",
  "Sri Lakshmi Vignesh Supermarket Rayachoty",
  "Reddaiah Supermarket Agraharam Surabhi",
  "RK Supermarket Rayachoty",
  "Bharath Supermarket Chinnamandema1",
  "Sri Venkateswara",
  "Gruha Lakshmi Supermarket Rayachoty",
  "KVR Supermarket",
  "Madeena Supermarket",
  "Quality Departmental Stores",
  "MVR Mart Angallu",
  "Sri Gurudatha Supermarket Guvvalacheruvu",
  "AMR Supermarket Nimmanapalle",
  "SR Supermarket Rayachoty",
  "Khans Supermarket Mudivedu",
  "Bismilla Supermarket Nambulapulakunta",
  "Hema Sri Supermarket Ramapuram",
  "AK Supermarket",
  "Baba Supermarket",
  "MSR Supermarket",
  "Sri Aruna Fancy and General Stores",
  "PS Super Mart Penagaluru",
  "Sri Lakshmi Narasimha Enterprises Rajampet",
  "Lakshmi Venkateswara Supermarket Nandimandalam",
  "Lakshmi Nilayam Mini Mart Srinivasapuram",
  "G K Mart Pulivendula",
  "Sri Hari Supermarket Rajampet",
  "Sugreeva Supermarket Vempalli",
  "M S Super Mart Chitvel",
  "SMB Supermarket Chilamakur",
  "Baddi Reddy Super Mart Nandalur",
  "Suriya Supermarket Vempalli",
  "Sankar S Mart Vempalli",
  "Chavva Nithish Supermarket Simhadripuram",
  "MM Supermarket Vempalli",
  "A to Z Supermarket Rajampeta",
  "Siva Supermarket",
  "Sri Balaji Supermarket Kondapuram",
  "SLV Mart Penukonda",
  "Family Supermarket",
  "Friends Supermarket Gorantla",
  "Ekshitha Lahanvi Supermart Atmakur Anantapur",
  "SLNS Super Mart Kuderu",
  "Vishnupriya Supermarket Anantapur",
  "Sri Ganesha Stores Vajrakarur",
  "S Mart Thimmampalli",
  "Sandeep Agencies Thogaragunta",
  "Lotus Supermarket Gooty",
  "Sri Lalitha Supermarket Talupula",
  "Golden Supermarket Tadipatri",
  "Lakshmi Supermarket Kalyanadurgam",
  "Akhil Manikanta Agency Kanaganapalli"
  ];